
# 12 Making the Cut

## Your Objective

Your dataset contains finish times for 37,250 marathon runners, along with their age, gender, and half-marathon split.

Your task is to calculate what percentage of the field finished within each of the following time bands:

- Sub 3:00
- 3:00 - 3:30
- 3:30 - 4:00
- 4:00 - 4:30
- 4:30 - 5:00
- 5:00 - 5:30
- 5:30 - 6:00
- 6:00+

NOTE: These bands should be lower-inclusive, meaning that a 3:30:00 finish time would fall under the 3:30 - 4:00 band, not 3:00 - 3:30.

See sample logic below:

![image](../images/SfefMhVeFNN7uf5xutpnN7P1HEI.avif)

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/marathon-data.csv')
df.head()

   age gender     split     final
0   33      M  01:05:38  02:08:51
1   32      M  01:06:26  02:09:28
2   31      M  01:06:49  02:10:42
3   38      M  01:06:16  02:13:45
4   31      M  01:06:32  02:13:59

In [8]:
df['final_minutes'] = pd.to_timedelta(df['final']).dt.total_seconds() / 60
band_edges = [0, 180, 210, 240, 270, 300, 330, 360, float('inf')]
band_labels = ['Sub 3', '3:00-3:30', '3:30-4:00', '4:00-4:30', '4:30-5:00', '5:00-5:30', '5:30-6:00', '6:00+']

df["band"] = pd.cut(df['final_minutes'], bins=band_edges, labels=band_labels, right=False)

df.band.value_counts(normalize=True).sort_index().to_frame(name='proportion')

           proportion
band
Sub 3        0.025906
3:00-3:30    0.081557
3:30-4:00    0.130980
4:00-4:30    0.171114
4:30-5:00    0.181638
5:00-5:30    0.169826
5:30-6:00    0.112161
6:00+        0.126819