# 08 Splitting the Field

## Your Objective

Your dataset contains the names of all the baseball players from the 2025 MLB season, along with their team(s) and position(s). A player qualifies for a position by starting at least 20 games at that position in the field or 5 games as a pitcher.

Your task is to aggregate this data and return a table counting the number of players at each position, sorted from highest to lowest.

NOTE: If a player has multiple positions, they will count towards each position they played.

See example below:

![image](../images/ZRbEZ7hA6BecHs9Q3Z5d4U7roY.avif)

In [1]:
import pandas as pd

df = pd.read_csv('data/baseball_positions.csv')

df.head()

            Name Team Position
0    Aaron Judge  NYY    OF/DH
1    Cal Raleigh  SEA     C/DH
2  Shohei Ohtani  LAD       DH
3      Juan Soto  NYM       OF
4   Tarik Skubal  DET       SP

In [2]:
df["Position"] = df["Position"].str.split("/").apply(lambda x: [i.strip() for i in x])
df.head()

            Name Team  Position
0    Aaron Judge  NYY  [OF, DH]
1    Cal Raleigh  SEA   [C, DH]
2  Shohei Ohtani  LAD      [DH]
3      Juan Soto  NYM      [OF]
4   Tarik Skubal  DET      [SP]

In [10]:
df = df.explode("Position")

df.head()

            Name Team Position
0    Aaron Judge  NYY       OF
0    Aaron Judge  NYY       DH
1    Cal Raleigh  SEA        C
1    Cal Raleigh  SEA       DH
2  Shohei Ohtani  LAD       DH

In [12]:
position_counts = df.groupby("Position").size().reset_index(name="Count").sort_values("Count", ascending=False)
position_counts.head(10)

  Position  Count
5       OF    294
7       SP    227
6       RP    222
4       DH    134
2       3B    127
1       2B    125
0       1B    114
3        C    106
8       SS     85