# 03 Rolling Up, Looking Back

## Your Objective

You’ve been given a table with raw data for individual coffee shop transactions. Your task is to aggregate the total sales by month and store, then calculate the month-over-month change in sales for each store (in dollars).

Example input and output:

![image](../images/KzJBIHeseB8isWzTTTEaMkobA.avif)

In [5]:
import pandas as pd

df = pd.read_csv('data/CoffeeShopSales.csv', parse_dates=['date'])
df.head()

,order_id,date,store,product,quantity,sales
0,1,2023-01-01,Lower Manhattan,Gourmet brewed coffee,2,6.0
1,2,2023-01-01,Lower Manhattan,Brewed Chai tea,2,6.2
2,3,2023-01-01,Lower Manhattan,Hot chocolate,2,9.0
3,4,2023-01-01,Lower Manhattan,Drip coffee,1,2.0
4,5,2023-01-01,Lower Manhattan,Brewed Chai tea,2,6.2

In [6]:
df.groupby(['store', df['date'].dt.month]).agg({'sales': 'sum'}).reset_index().rename(columns={'date': 'month'})

              store  month     sales
0           Astoria      1  27313.66
1           Astoria      2  25105.34
2           Astoria      3  32835.43
3           Astoria      4  39477.61
4           Astoria      5  52428.76
5           Astoria      6  55083.11
6    Hell's Kitchen      1  27820.65
7    Hell's Kitchen      2  25719.80
8    Hell's Kitchen      3  33110.57
9    Hell's Kitchen      4  40304.14
10   Hell's Kitchen      5  52598.93
11   Hell's Kitchen      6  56957.08
12  Lower Manhattan      1  26543.43
13  Lower Manhattan      2  25320.05
14  Lower Manhattan      3  32888.68
15  Lower Manhattan      4  39159.33
16  Lower Manhattan      5  51700.07
17  Lower Manhattan      6  54445.69

In [8]:
may_astoria = df[(df['store'] == 'Astoria') & (df['date'].dt.month == 5)]
april_astoria = df[(df['store'] == 'Astoria') & (df['date'].dt.month == 4)]

difference = may_astoria['sales'].sum() - april_astoria['sales'].sum()
print(f"The difference in sales for Astoria between May and April is: ${difference:.2f}")

The difference in sales for Astoria between May and April is: $12951.15